In [12]:
import numpy as np
import cmath

a = np.array([[0.96, 1.72],
              [2.28, 0.96]])

eig_vals, eig_vecs = np.linalg.eig(a)
eig_vals


array([ 2.94030301, -1.02030301])

In [2]:
eig_vecs


array([[ 0.65574385, -0.65574385],
       [ 0.75498344,  0.75498344]])

In [3]:
# singular values:

sing_vals = np.array([np.sqrt(eig_val) for eig_val in np.linalg.eig(a@a.T)[0]])


In [4]:
sing_vals


array([1., 3.])

In [45]:
def get_eig(x):
    """ In descending order of eigenvalues"""
    eigenValues, eigenVectors = np.linalg.eig(x)
    idx = eigenValues.argsort()[::-1]
    eigenValues = eigenValues[idx]
    eigenVectors = eigenVectors[:, idx]
    return eigenValues, eigenVectors


def get_svd(x):  # с точностью до знака воспроизводит матрицу х
    sing_vals = np.array([np.sqrt(eig_val)
                         for eig_val in get_eig(x@x.T)[0]])
    left_sing_vecs = get_eig(x@x.T)[1]  # u
    right_sing_vecs = get_eig(x.T@x)[1]  # v
    return left_sing_vecs, sing_vals, right_sing_vecs.T


U, S, Vh = get_svd(a)
# U@np.diag(S)@Vh
U, S, Vh
U@np.diag(S)@Vh


array([[-0.96, -1.72],
       [-2.28, -0.96]])

In [48]:
a


array([[0.96, 1.72],
       [2.28, 0.96]])

In [63]:
import plotly.express as px
import pandas as pd
df = pd.DataFrame(a)
px.scatter(x=df[0], y=df[1])


In [64]:
df


0     1
0  0.96  1.72
1  2.28  0.96

In [129]:
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])
a = b
centered = a - a.mean(axis=0)
n, m = centered.shape
covmat = np.cov(centered.T)  # unbiased
covmat, centered.T@centered


(array([[4., 4.],
        [4., 4.]]),
 array([[8., 8.],
        [8., 8.]]))

In [130]:
y = centered/np.sqrt(n-1)
y


array([[-1.41421356, -1.41421356],
       [ 0.        ,  0.        ],
       [ 1.41421356,  1.41421356]])

In [131]:
covmat


array([[4., 4.],
       [4., 4.]])

In [132]:
centered.T@centered


array([[8., 8.],
       [8., 8.]])

In [133]:
c = y.T@y
c


array([[4., 4.],
       [4., 4.]])

In [148]:
def get_pca(x):
    centered = x - x.mean(axis=0)
    n, m = centered.shape
    y = centered/np.sqrt(n-1)
    _, _, vh = get_svd(y)
    pr_components = vh.T
    return pr_components


t = b[0]  # projectable vector

for pc in get_pca(b).T:
    projection = pc@t
    print(projection)


2.1213203435596424
0.7071067811865475


In [32]:
left_sing_vecs = np.linalg.eig(a@a.T)[1]  # u
right_sing_vecs = np.linalg.eig(a.T@a)[1]  # v
left_sing_vecs, right_sing_vecs


(array([[-0.8, -0.6],
        [ 0.6, -0.8]]),
 array([[ 0.8, -0.6],
        [ 0.6,  0.8]]))

In [35]:
U, S, Vh = np.linalg.svd(a)

V = Vh.T
U, S, Vh


(array([[-0.6, -0.8],
        [-0.8,  0.6]]),
 array([3., 1.]),
 array([[-0.8, -0.6],
        [ 0.6, -0.8]]))

In [7]:
U


array([[-0.6, -0.8],
       [-0.8,  0.6]])

In [8]:
V


array([[-0.8,  0.6],
       [-0.6, -0.8]])